// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeB8IjPzMdF90T_KdYJQZI_TSblqWE5HA',
    appId: '1:506370116318:web:5d574b88eedf5eee0d904f',
    messagingSenderId: '506370116318',
    projectId: 'dev-meet-e4e85',
    authDomain: 'dev-meet-e4e85.firebaseapp.com',
    storageBucket: 'dev-meet-e4e85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBsf4msiQg9900wLLrLHHbQwV0P5GaAng',
    appId: '1:506370116318:android:3e05b3c1f7e9c8ae0d904f',
    messagingSenderId: '506370116318',
    projectId: 'dev-meet-e4e85',
    storageBucket: 'dev-meet-e4e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcD53zDn1ecxUI_ASpfkOY5-vhPQ8TFVo',
    appId: '1:506370116318:ios:c34daa520c81a0fd0d904f',
    messagingSenderId: '506370116318',
    projectId: 'dev-meet-e4e85',
    storageBucket: 'dev-meet-e4e85.appspot.com',
    iosClientId: '506370116318-gmj3v3ebn5pssmhimgjp6udp7n8tcc1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.devMeets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcD53zDn1ecxUI_ASpfkOY5-vhPQ8TFVo',
    appId: '1:506370116318:ios:c34daa520c81a0fd0d904f',
    messagingSenderId: '506370116318',
    projectId: 'dev-meet-e4e85',
    storageBucket: 'dev-meet-e4e85.appspot.com',
    iosClientId: '506370116318-gmj3v3ebn5pssmhimgjp6udp7n8tcc1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.devMeets',
  );
}
